//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillagePaint.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Customer
    {
        public long customerID { get; set; }
        public string CardNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string Cell { get; set; }
        public string AddressStreet { get; set; }
        public string AddressSuburb { get; set; }
        public string AddressCity { get; set; }
        public string ZipCode { get; set; }
    }
}
